name: 'Sharepoint release'

on:
  release:
    types: created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: Cloning repo # This step is required
      uses: actions/checkout@v2

    - name: Publish to Sharepoint
      uses: obrassard/action-sharepoint-publish@v1.0.1
      with:
       site_url: 'https://vodafone.sharepoint.com.mcas.ms/sites/Github_sharepoint'
       library_folder: 'documents/README.md'
       sharepoint_user: vamsi.dangeti@vodafone.com
       sharepoint_password: "Failure_Test@2023"
